alias l="colorls -a"
alias la="colorls -la"
alias lad="colorls -la --sd"
alias lar="colorls -la --report"
alias ld="colorls -a --sd"
alias ldr="colorls -a --sd --report"
alias lf="colorls -a --sf"
alias laf="colorls -la --sf"
alias ll="colorls *"
alias lla="colorls * -la --sd"
alias llr="colorls * -la --sd --report"
alias lr="colorls -a --report"

